apiVersion: apps/v1
kind: Deployment
metadata:
  labels: &myLabels
    app: voting-app
    part: event-api
  name: nodejs-event-api
spec:
  replicas: 1
  selector:
    matchLabels: *myLabels
  template:
    metadata:
      labels: *myLabels
    spec:
      containers:
        - name: events-socketio
          image: "vorkurk/nodejs-event-app:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: rabbitmq-config
          ports:
            - containerPort: 9000
              name: default