name: Push Images to repository
on:
  push:
    branches:
      - 'main'
jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: src/golang
          tags: vorkurk/go-voting-app:latest
      - name: kubectl config
        run: |
          echo '${{ secrets.KUBEC }}' > kubeconfig.yml
          export KUBECONFIG=$(pwd)/kubeconfig.yml
          kubectl version
          kubectl apply -n votingapp -f extras/kubernetes/golang.yml
  react:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: src/react
          tags: vorkurk/react-voting-app:latest
      - name: kubectl config
        run: |
          echo '${{ secrets.KUBEC }}' > kubeconfig.yml
          export KUBECONFIG=$(pwd)/kubeconfig.yml
          kubectl version
          kubectl apply -n votingapp -f extras/kubernetes/react.yml
  nodejs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: src/nodejs
          tags: vorkurk/nodejs-event-app:latest
      - name: kubectl config
        run: |
          echo '${{ secrets.KUBEC }}' > kubeconfig.yml
          export KUBECONFIG=$(pwd)/kubeconfig.yml
          kubectl version
          kubectl apply -n votingapp -f extras/kubernetes/nodejs.yml