name: Deploy
on:
  workflow_run:
    workflows:
      - PushImages
    types:
      - completed
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: deployment
        run: |
          echo '${{ secrets.KUBEC }}' > kubeconfig.yml
          export KUBECONFIG=$(pwd)/kubeconfig.yml
          kubectl version
          helm upgrade voting-app extras/voting-app --set image.tag=$(git rev-parse --short "$GITHUB_SHA") --namespace votingapp --create-namespace --install