name: PushImages
on:
  push:
    branches:
      - 'main'
jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set the value
        id: step_one
        run: |
          echo "image=vorkurk/go-voting-app:$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: src/golang
          tags: ${{ env.image }}
  react:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set the value
        id: step_one
        run: |
          echo "image=vorkurk/react-voting-app:$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: src/react
          tags: ${{ env.image }}
  nodejs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set the value
        id: step_one
        run: |
          echo "image=vorkurk/nodejs-event-app:$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: src/nodejs
          tags: ${{ env.image }}